Add single integration test
ScottyLabs/dining-api pull request #153
Opened 2024-09-08 23:26 UTC by cirex-web

# Description

I was bored and wanted to refactor the code, but I realized that this codebase was severly lacking in tests so I wrote a single integration test. (more to come, probably)

 I was going to use `bun test`, but its mocking is a bit subpar, so I set up Jest (with Babel) instead. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

**Test Configuration**:

- Node.js version:
- Python version:
- Desktop/Mobile:
- OS:
- Browser:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-09-08 23:41 UTC, cirex-web commented
okay i have no idea why the test github Action isn't running 😭

2024-09-08 23:48 UTC, GhostOf0days commented
> okay i have no idea why the test github Action isn't running 😭 (it ran for the first commit)

this has happened to me so many times lol. usually runs if i close and re-open prs.

2024-09-09 01:39 UTC, cirex-web commented
nvm I fixed the github action for tests

2024-09-09 01:43 UTC, GhostOf0days commented
what was the issue?

2024-09-09 01:44 UTC, cirex-web commented on .github/workflows/test.yml
> +    types: [opened, reopened, synchronize]
just had to add synchronize

2024-09-09 01:46 UTC, cirex-web commented on .github/workflows/test.yml
> +    types: [opened, reopened, synchronize]
https://github.com/orgs/community/discussions/24567

2024-09-09 01:49 UTC, GhostOf0days commented on .github/workflows/test.yml
> +    types: [opened, reopened, synchronize]
Oh I see. Maybe we also need to add in this to the GitHub Action for CMUEats.

2024-09-09 01:56 UTC, cirex-web commented on .github/workflows/test.yml
> +    types: [opened, reopened, synchronize]
yes

2024-09-09 02:36 UTC, GhostOf0days commented
I think code looks good from first glance. I'll look more into it tomorrow. Small request: can you please update the documentation to include https://bun.sh/docs/cli/update and https://bun.sh/docs/cli/outdated since you also updated ReadMe in this PR? We can also add this to CMUEats after.

2024-09-09 02:39 UTC, GhostOf0days requested changes
Thank you for this. Looks good to me. However, I have one small request: can you please update the documentation to include https://bun.sh/docs/cli/update and https://bun.sh/docs/cli/outdated since you also updated the ReadMe in this PR? We can also add this to CMUEats after.

2024-09-09 02:40 UTC, cirex-web commented
something like this? idk what you meant exactly lol

## Before submitting a PR

- Make sure all tests pass with `bun run test` or `bun run test --watch` for watch mode.
- Run `bun update` to update all dependencies to the latest version (`bun outdated` to see what will get updated)

2024-09-09 02:47 UTC, GhostOf0days commented
Maybe this: Run `bun outdated` to see what dependencies are outdated. Run `bun update` to update all outdated dependencies to the latest version. 

(sorry. i would do this myself, but my laptop's dead, and i'm using github mobile. 😂)

2024-09-09 02:51 UTC, GhostOf0days approved these changes

2024-09-09 02:51 UTC, merged